/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import MODEL.Funcionario;
import java.awt.CardLayout;
import java.awt.Color;

/**
 *
 * @author Melhor De Mim
 */
public class GHome extends javax.swing.JFrame {

    

    /**
     * Creates new form GHome
     */
    Color defaultColor, ClickedColor, inDefaultColor, inClickedColor;
    CardLayout cardLayout;
    public GHome(Funcionario f) {
        initComponents();
        System.out.println(f.getNome());
        
        defaultColor = new Color(60, 179, 113);
        ClickedColor = new Color(204, 255, 204);
        inDefaultColor = new Color(204, 255, 204);
        inClickedColor = new Color(60, 179, 113);

        cardLayout = (CardLayout) (pnlCards.getLayout());
        cardLayout.show(pnlCards, "HomePanel");
        imgLabel.setIcon(new javax.swing.ImageIcon(""));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        btnBloco = new javax.swing.JPanel();
        btnFunc = new javax.swing.JPanel();
        btnSair = new javax.swing.JPanel();
        btnCela = new javax.swing.JPanel();
        imgLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnTurnos = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        btnFuncao = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        btnSair1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        pnlCards = new javax.swing.JPanel();
        RelactPanel = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblTurno = new javax.swing.JTable();
        HomePanel = new javax.swing.JPanel();
        imgLabel1 = new javax.swing.JLabel();
        letterLabel2 = new javax.swing.JLabel();
        letterLabel3 = new javax.swing.JLabel();
        letterLabel4 = new javax.swing.JLabel();
        lblNomeG = new javax.swing.JLabel();
        letterLabel6 = new javax.swing.JLabel();
        lblNomeG1 = new javax.swing.JLabel();
        lblTurnoG = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblFuncionario1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(60, 179, 113));

        btnBloco.setBackground(new java.awt.Color(60, 179, 113));

        javax.swing.GroupLayout btnBlocoLayout = new javax.swing.GroupLayout(btnBloco);
        btnBloco.setLayout(btnBlocoLayout);
        btnBlocoLayout.setHorizontalGroup(
            btnBlocoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        btnBlocoLayout.setVerticalGroup(
            btnBlocoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        btnFunc.setBackground(new java.awt.Color(60, 179, 113));

        javax.swing.GroupLayout btnFuncLayout = new javax.swing.GroupLayout(btnFunc);
        btnFunc.setLayout(btnFuncLayout);
        btnFuncLayout.setHorizontalGroup(
            btnFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        btnFuncLayout.setVerticalGroup(
            btnFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        btnSair.setBackground(new java.awt.Color(60, 179, 113));

        javax.swing.GroupLayout btnSairLayout = new javax.swing.GroupLayout(btnSair);
        btnSair.setLayout(btnSairLayout);
        btnSairLayout.setHorizontalGroup(
            btnSairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        btnSairLayout.setVerticalGroup(
            btnSairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        btnCela.setBackground(new java.awt.Color(60, 179, 113));

        javax.swing.GroupLayout btnCelaLayout = new javax.swing.GroupLayout(btnCela);
        btnCela.setLayout(btnCelaLayout);
        btnCelaLayout.setHorizontalGroup(
            btnCelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        btnCelaLayout.setVerticalGroup(
            btnCelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        imgLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Melhor De Mim\\OneDrive - academiabai.co.ao\\Projecto De Pro Implementação\\img\\Icons-Bencao-04.png")); // NOI18N

        jLabel6.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        jLabel6.setText("S I S T G P");

        btnTurnos.setBackground(new java.awt.Color(60, 179, 113));

        jLabel20.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("RELATORIO");
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel20MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel20MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout btnTurnosLayout = new javax.swing.GroupLayout(btnTurnos);
        btnTurnos.setLayout(btnTurnosLayout);
        btnTurnosLayout.setHorizontalGroup(
            btnTurnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnTurnosLayout.createSequentialGroup()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnTurnosLayout.setVerticalGroup(
            btnTurnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        btnFuncao.setBackground(new java.awt.Color(60, 179, 113));

        jLabel21.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("HOME");
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel21MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel21MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout btnFuncaoLayout = new javax.swing.GroupLayout(btnFuncao);
        btnFuncao.setLayout(btnFuncaoLayout);
        btnFuncaoLayout.setHorizontalGroup(
            btnFuncaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnFuncaoLayout.setVerticalGroup(
            btnFuncaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
        );

        btnSair1.setBackground(new java.awt.Color(60, 179, 113));

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("SAIR");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel10MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel10MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout btnSair1Layout = new javax.swing.GroupLayout(btnSair1);
        btnSair1.setLayout(btnSair1Layout);
        btnSair1Layout.setHorizontalGroup(
            btnSair1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnSair1Layout.setVerticalGroup(
            btnSair1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(imgLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnCela, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTurnos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFuncao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSair1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBloco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(imgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBloco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTurnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSair1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addComponent(btnCela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
        );

        jSplitPane1.setLeftComponent(jPanel2);

        pnlCards.setLayout(new java.awt.CardLayout());

        RelactPanel.setBackground(new java.awt.Color(204, 255, 204));

        jPanel9.setBackground(new java.awt.Color(204, 255, 204));

        tblTurno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Descrição"
            }
        )
        {
            public boolean isCellEditable(int row, int column){
                return false;
            }
        }
    );
    tblTurno.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            tblTurnoMouseClicked(evt);
        }
    });
    jScrollPane6.setViewportView(tblTurno);

    javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
    jPanel9.setLayout(jPanel9Layout);
    jPanel9Layout.setHorizontalGroup(
        jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
            .addContainerGap(15, Short.MAX_VALUE)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );
    jPanel9Layout.setVerticalGroup(
        jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel9Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(17, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout RelactPanelLayout = new javax.swing.GroupLayout(RelactPanel);
    RelactPanel.setLayout(RelactPanelLayout);
    RelactPanelLayout.setHorizontalGroup(
        RelactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(RelactPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(40, Short.MAX_VALUE))
    );
    RelactPanelLayout.setVerticalGroup(
        RelactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(RelactPanelLayout.createSequentialGroup()
            .addGap(37, 37, 37)
            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(391, Short.MAX_VALUE))
    );

    pnlCards.add(RelactPanel, "TurnoPanel");

    HomePanel.setBackground(new java.awt.Color(204, 255, 204));

    imgLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Melhor De Mim\\OneDrive - academiabai.co.ao\\Projecto De Pro Implementação\\img\\Icons-Bencao-04.png")); // NOI18N

    letterLabel2.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
    letterLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    letterLabel2.setText("S I S T E M A  D E  G E S T Ã O  ");

    letterLabel3.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
    letterLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    letterLabel3.setText("Bem Vindo");

    letterLabel4.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
    letterLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    letterLabel4.setText("P R I S I O N A L");

    lblNomeG.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
    lblNomeG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblNomeG.setText("Nome:");

    letterLabel6.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
    letterLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    letterLabel6.setText("Nome:");

    lblNomeG1.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
    lblNomeG1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblNomeG1.setText("Turno:");

    lblTurnoG.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
    lblTurnoG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblTurnoG.setText("Turno:");

    tblFuncionario1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
    tblFuncionario1.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null}
        },
        new String [] {
            "Nome", "Endereço", "Sexo", "Estado Civil", "Data de Nascimento", "Data De Admissão", "Função"
        }

    )
    {
        public boolean isCellEditable(int row, int column){
            return false;
        }
    }
    );
    jScrollPane2.setViewportView(tblFuncionario1);

    javax.swing.GroupLayout HomePanelLayout = new javax.swing.GroupLayout(HomePanel);
    HomePanel.setLayout(HomePanelLayout);
    HomePanelLayout.setHorizontalGroup(
        HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(HomePanelLayout.createSequentialGroup()
            .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(HomePanelLayout.createSequentialGroup()
                    .addGap(29, 29, 29)
                    .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomePanelLayout.createSequentialGroup()
                            .addComponent(imgLabel1)
                            .addGap(228, 228, 228))
                        .addComponent(letterLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomePanelLayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomePanelLayout.createSequentialGroup()
                                    .addComponent(letterLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(207, 207, 207))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomePanelLayout.createSequentialGroup()
                                    .addComponent(letterLabel4)
                                    .addGap(169, 169, 169))))))
                .addGroup(HomePanelLayout.createSequentialGroup()
                    .addGap(45, 45, 45)
                    .addComponent(letterLabel6)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(lblNomeG)
                    .addGap(161, 161, 161)
                    .addComponent(lblNomeG1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(lblTurnoG)))
            .addGap(0, 40, Short.MAX_VALUE))
        .addGroup(HomePanelLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane2)
            .addContainerGap())
    );
    HomePanelLayout.setVerticalGroup(
        HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(HomePanelLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(imgLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(letterLabel3)
            .addGap(18, 18, 18)
            .addComponent(letterLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(12, 12, 12)
            .addComponent(letterLabel4)
            .addGap(18, 18, 18)
            .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblNomeG1)
                .addComponent(letterLabel6)
                .addComponent(lblNomeG)
                .addComponent(lblTurnoG))
            .addGap(75, 75, 75)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(125, Short.MAX_VALUE))
    );

    pnlCards.add(HomePanel, "HomePanel");

    jSplitPane1.setRightComponent(pnlCards);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jSplitPane1)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        dispose();
        new Login().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MousePressed

    private void jLabel10MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseReleased

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        // TODO add your handling code here:
        cardLayout.show(pnlCards, "RelactPanel");
        imgLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Melhor De Mim\\OneDrive - academiabai.co.ao\\Projecto De Pro Implementação\\SistGP\\src\\IMG\\Icons-Bencao-04.png"));
//        tbModelT = new DefaultTableModel() {
//
//            @Override
//            public boolean isCellEditable(int row, int column) {
//                return false;
//
//            }
//        };
//
//        new TurnoController().CarregarTabela(tbModelT, tblTurno);
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel20MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel20MousePressed

    private void jLabel20MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel20MouseReleased

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // TODO add your handling code here:
        cardLayout.show(pnlCards, "HomePanel");
        imgLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Melhor De Mim\\OneDrive - academiabai.co.ao\\Projecto De Pro Implementação\\SistGP\\src\\IMG\\Icons-Bencao-04.png"));
//        tbModelFunc = new DefaultTableModel() {
//
//            @Override
//            public boolean isCellEditable(int row, int column) {
//                return false;
//
//            }
//        };
//
//        new FuncaoController().CarregarTabela(tbModelFunc, tblFuncao);
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel21MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel21MousePressed

    private void jLabel21MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel21MouseReleased

    private void tblTurnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTurnoMouseClicked
        // TODO add your handling code here:
//        btnExTurno.setEnabled(true);
//        int j = tblTurno.getSelectedRow();
//        turno = tbModelT.getValueAt(j, 0).toString();
//
//        btnEdTurno.setEnabled(false);
//        if (evt.getClickCount() == 2) {
//            edit = true;
//            int i = tblTurno.getSelectedRow();
//            txtTurno.setText(tbModelT.getValueAt(i, 0).toString());
//            btnEdTurno.setEnabled(true);
//            btnCadTurno.setEnabled(false);
//            turno = txtTurno.getText();
//            btnExTurno.setEnabled(false);
//        }
    }//GEN-LAST:event_tblTurnoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GHome(new Funcionario()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HomePanel;
    private javax.swing.JPanel RelactPanel;
    private javax.swing.JPanel btnBloco;
    private javax.swing.JPanel btnCela;
    private javax.swing.JPanel btnFunc;
    private javax.swing.JPanel btnFuncao;
    private javax.swing.JPanel btnSair;
    private javax.swing.JPanel btnSair1;
    private javax.swing.JPanel btnTurnos;
    private javax.swing.JLabel imgLabel;
    private javax.swing.JLabel imgLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblNomeG;
    private javax.swing.JLabel lblNomeG1;
    private javax.swing.JLabel lblTurnoG;
    private javax.swing.JLabel letterLabel2;
    private javax.swing.JLabel letterLabel3;
    private javax.swing.JLabel letterLabel4;
    private javax.swing.JLabel letterLabel6;
    private javax.swing.JPanel pnlCards;
    private javax.swing.JTable tblFuncionario1;
    private javax.swing.JTable tblTurno;
    // End of variables declaration//GEN-END:variables
}
