/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import java.awt.Color;

/**
 *
 * @author Melhor De Mim
 */
public class LoginConfSenha extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    Color defaultColor,ClickedColor,white; 
    public LoginConfSenha() {
        initComponents();
        
        defaultColor = new Color(204,255,204);
        ClickedColor =new Color(60,179,113);
        white = new Color(255,255,255);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NovaSenhaPanel = new javax.swing.JPanel();
        txtNovaSenha = new javax.swing.JPasswordField();
        txtUsuarioNovaSenha = new javax.swing.JTextField();
        txtConfNovaSenha = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        btnEntrar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        NovaSenhaPanel.setBackground(new java.awt.Color(204, 255, 204));
        NovaSenhaPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNovaSenha.setBackground(new java.awt.Color(204, 255, 204));
        txtNovaSenha.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        txtNovaSenha.setText("jPasswordField1");
        txtNovaSenha.setBorder(null);
        NovaSenhaPanel.add(txtNovaSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 160, -1));

        txtUsuarioNovaSenha.setBackground(new java.awt.Color(204, 255, 204));
        txtUsuarioNovaSenha.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        txtUsuarioNovaSenha.setText("Usuario");
        txtUsuarioNovaSenha.setBorder(null);
        txtUsuarioNovaSenha.setEnabled(false);
        NovaSenhaPanel.add(txtUsuarioNovaSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 160, -1));

        txtConfNovaSenha.setBackground(new java.awt.Color(204, 255, 204));
        txtConfNovaSenha.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        txtConfNovaSenha.setText("jPasswordField1");
        txtConfNovaSenha.setBorder(null);
        NovaSenhaPanel.add(txtConfNovaSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 160, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel7.setText("Criar Senha");
        NovaSenhaPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 260, 60));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        NovaSenhaPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 170, 10));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        NovaSenhaPanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 170, 10));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        NovaSenhaPanel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 170, 10));

        btnEntrar.setBackground(new java.awt.Color(204, 255, 204));
        btnEntrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Entrar");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel1MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout btnEntrarLayout = new javax.swing.GroupLayout(btnEntrar);
        btnEntrar.setLayout(btnEntrarLayout);
        btnEntrarLayout.setHorizontalGroup(
            btnEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        btnEntrarLayout.setVerticalGroup(
            btnEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
        );

        NovaSenhaPanel.add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        NovaSenhaPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 30, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(NovaSenhaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 257, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(NovaSenhaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        btnEntrar.setBackground(ClickedColor);
        //        jLabel1.setForeground(white);
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseReleased
        btnEntrar.setBackground(defaultColor);
    }//GEN-LAST:event_jLabel1MouseReleased

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginConfSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginConfSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginConfSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginConfSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginConfSenha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel NovaSenhaPanel;
    private javax.swing.JPanel btnEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPasswordField txtConfNovaSenha;
    private javax.swing.JPasswordField txtNovaSenha;
    private javax.swing.JTextField txtUsuarioNovaSenha;
    // End of variables declaration//GEN-END:variables
}
