/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import CONTROLLER.CelaController;
import CONTROLLER.CrimeController;
import CONTROLLER.EJulgadoController;
import CONTROLLER.FuncionarioController;
import CONTROLLER.PrisioneiroController;
import MODEL.Bloco;
import MODEL.CelaPK;
import MODEL.Crime;
import MODEL.EJulgado;
import MODEL.Esquadra;
import MODEL.Funcionario;
import MODEL.JulgamentoPK;
import MODEL.Prisioneiro;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.HeadlessException;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Melhor De Mim
 */
public class GHome extends javax.swing.JFrame {

    /**
     * Creates new form GHome
     */
    String Bloco;
    Color defaultColor, ClickedColor, inDefaultColor, inClickedColor;
    CardLayout cardLayout;

    DefaultTableModel tbModelPris;
    DefaultTableModel tbModelF = new DefaultTableModel() {

        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }

    };
    ;
    PrisioneiroController prisController;
    CelaController cController = new CelaController();
    FuncionarioController fController = new FuncionarioController();

    public GHome(Funcionario f, Bloco b) {
        initComponents();
        lblTurnoG.setText(f.getIdTurno().getTurno());
        lblNomeG.setText(f.getNome());
        lblBlocoG.setText(b.getDescricao());
        Bloco = b.getDescricao();

        imgLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Icons-Bencao-04.png")));

        defaultColor = new Color(60, 179, 113);
        ClickedColor = new Color(204, 255, 204);
        inDefaultColor = new Color(204, 255, 204);
        inClickedColor = new Color(60, 179, 113);

        cardLayout = (CardLayout) (pnlCards.getLayout());
        cardLayout.show(pnlCards, "HomePanel");
        imgLabel.setIcon(new javax.swing.ImageIcon(""));

        fController.TabelaG(tbModelF, tblFuncionario1, lblTurnoG.getText(), lblBlocoG.getText(), lblNomeG.getText());
    }

    private void CarregarTabelaPris(JTable a) {
        Object[] columnNames = {"Nº Do BI", "Nome", "Sexo", "Crime", "Cela", "Pena"};
        var criController = new CrimeController();
        var ejController = new EJulgadoController();
        prisController = new PrisioneiroController();
        cController = new CelaController();

        tbModelPris = new DefaultTableModel(columnNames, 0) {

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;

            }
        };
        for (int i = 0; i < prisController.findAll().size(); i++) {

            Object[] lista = {
                prisController.findAll().get(i).getNumBI(),
                prisController.findAll().get(i).getNome(),
                prisController.findAll().get(i).getSexo(),
                criController.Find(prisController.findAll().get(i).getNumBI()).get(i).getDescricao(),
                cController.Find(prisController.findAll().get(i).getIdBloco().getCelaPK().getIdBloco()).get(i).getCelaPK().getDescricao(),
                ejController.Find(prisController.findAll().get(i).getNumBI()).get(i).getPena()
            };

            tbModelPris.addRow(lista);
        }
        a.setModel(tbModelPris);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        btnBloco = new javax.swing.JPanel();
        btnFunc = new javax.swing.JPanel();
        btnSair = new javax.swing.JPanel();
        btnCela = new javax.swing.JPanel();
        imgLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnRelact = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        btnHome = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        btnSair1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        pnlCards = new javax.swing.JPanel();
        RelactPanel = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblRelactorio = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jSeparator20 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lbldataEntrada = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator26 = new javax.swing.JSeparator();
        lblCrime = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator27 = new javax.swing.JSeparator();
        lblEsquadra = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator28 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        lblTribunal = new javax.swing.JLabel();
        jSeparator29 = new javax.swing.JSeparator();
        lblPena = new javax.swing.JLabel();
        jSeparator30 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        lblBloco = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator31 = new javax.swing.JSeparator();
        jSeparator32 = new javax.swing.JSeparator();
        lblCela = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        HomePanel = new javax.swing.JPanel();
        imgLabel1 = new javax.swing.JLabel();
        letterLabel2 = new javax.swing.JLabel();
        letterLabel3 = new javax.swing.JLabel();
        letterLabel4 = new javax.swing.JLabel();
        lblNomeG = new javax.swing.JLabel();
        letterLabel6 = new javax.swing.JLabel();
        lblNomeG1 = new javax.swing.JLabel();
        lblTurnoG = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblFuncionario1 = new javax.swing.JTable();
        lblBlocoG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(60, 179, 113));

        btnBloco.setBackground(new java.awt.Color(60, 179, 113));

        javax.swing.GroupLayout btnBlocoLayout = new javax.swing.GroupLayout(btnBloco);
        btnBloco.setLayout(btnBlocoLayout);
        btnBlocoLayout.setHorizontalGroup(
            btnBlocoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        btnBlocoLayout.setVerticalGroup(
            btnBlocoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        btnFunc.setBackground(new java.awt.Color(60, 179, 113));

        javax.swing.GroupLayout btnFuncLayout = new javax.swing.GroupLayout(btnFunc);
        btnFunc.setLayout(btnFuncLayout);
        btnFuncLayout.setHorizontalGroup(
            btnFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        btnFuncLayout.setVerticalGroup(
            btnFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        btnSair.setBackground(new java.awt.Color(60, 179, 113));

        javax.swing.GroupLayout btnSairLayout = new javax.swing.GroupLayout(btnSair);
        btnSair.setLayout(btnSairLayout);
        btnSairLayout.setHorizontalGroup(
            btnSairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        btnSairLayout.setVerticalGroup(
            btnSairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        btnCela.setBackground(new java.awt.Color(60, 179, 113));

        javax.swing.GroupLayout btnCelaLayout = new javax.swing.GroupLayout(btnCela);
        btnCela.setLayout(btnCelaLayout);
        btnCelaLayout.setHorizontalGroup(
            btnCelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        btnCelaLayout.setVerticalGroup(
            btnCelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel6.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        jLabel6.setText("S I S T G P");

        btnRelact.setBackground(new java.awt.Color(60, 179, 113));

        jLabel20.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("RELATORIO");
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel20MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel20MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout btnRelactLayout = new javax.swing.GroupLayout(btnRelact);
        btnRelact.setLayout(btnRelactLayout);
        btnRelactLayout.setHorizontalGroup(
            btnRelactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnRelactLayout.setVerticalGroup(
            btnRelactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        btnHome.setBackground(new java.awt.Color(60, 179, 113));

        jLabel21.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("HOME");
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel21MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel21MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout btnHomeLayout = new javax.swing.GroupLayout(btnHome);
        btnHome.setLayout(btnHomeLayout);
        btnHomeLayout.setHorizontalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHomeLayout.createSequentialGroup()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnHomeLayout.setVerticalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHomeLayout.createSequentialGroup()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnSair1.setBackground(new java.awt.Color(60, 179, 113));

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("SAIR");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel10MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel10MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout btnSair1Layout = new javax.swing.GroupLayout(btnSair1);
        btnSair1.setLayout(btnSair1Layout);
        btnSair1Layout.setHorizontalGroup(
            btnSair1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnSair1Layout.setVerticalGroup(
            btnSair1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(imgLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnCela, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRelact, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSair1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBloco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(imgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBloco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRelact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSair1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addComponent(btnCela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
        );

        jSplitPane1.setLeftComponent(jPanel2);

        pnlCards.setLayout(new java.awt.CardLayout());

        RelactPanel.setBackground(new java.awt.Color(204, 255, 204));
        RelactPanel.setPreferredSize(new java.awt.Dimension(564, 530));

        jPanel9.setBackground(new java.awt.Color(204, 255, 204));

        tblRelactorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Descrição"
            }
        )
        {
            public boolean isCellEditable(int row, int column){
                return false;
            }
        }
    );
    tblRelactorio.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            tblRelactorioMouseClicked(evt);
        }
    });
    jScrollPane6.setViewportView(tblRelactorio);

    javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
    jPanel9.setLayout(jPanel9Layout);
    jPanel9Layout.setHorizontalGroup(
        jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );
    jPanel9Layout.setVerticalGroup(
        jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel9Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel1.setBackground(new java.awt.Color(204, 255, 204));

    jSeparator20.setBackground(new java.awt.Color(255, 255, 255));

    jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
    jLabel5.setText("Nome:");

    lblNome.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
    lblNome.setText("------------------------");

    lbldataEntrada.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
    lbldataEntrada.setText("-------------");

    jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
    jLabel7.setText("Data De Entrada: ");

    jSeparator26.setBackground(new java.awt.Color(255, 255, 255));

    lblCrime.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
    lblCrime.setText("-----------------------");

    jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
    jLabel8.setText("Crime:");

    jSeparator27.setBackground(new java.awt.Color(255, 255, 255));

    lblEsquadra.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
    lblEsquadra.setText("-------------------");

    jLabel9.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
    jLabel9.setText("Esquadra:");

    jSeparator28.setBackground(new java.awt.Color(255, 255, 255));

    jLabel11.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
    jLabel11.setText("Tribunal:");

    lblTribunal.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
    lblTribunal.setText("-------------------");

    jSeparator29.setBackground(new java.awt.Color(255, 255, 255));

    lblPena.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
    lblPena.setText("-------------------");

    jSeparator30.setBackground(new java.awt.Color(255, 255, 255));

    jLabel12.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
    jLabel12.setText("Pena:");

    lblBloco.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
    lblBloco.setText("-------------------");

    jLabel13.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
    jLabel13.setText("Bloco:");

    jSeparator31.setBackground(new java.awt.Color(255, 255, 255));

    jSeparator32.setBackground(new java.awt.Color(255, 255, 255));

    lblCela.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
    lblCela.setText("-------------------");

    jLabel14.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
    jLabel14.setText("Cela:");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 517, Short.MAX_VALUE)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jSeparator20, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbldataEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jSeparator26, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCrime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jSeparator27, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEsquadra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jSeparator28, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTribunal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jSeparator29, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jSeparator30, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBloco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jSeparator31, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator32, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCela, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 201, Short.MAX_VALUE)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblNome))
                        .addGap(5, 5, 5)
                        .addComponent(jSeparator20, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(lbldataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addComponent(jSeparator26, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(lblCrime))
                        .addGap(5, 5, 5)
                        .addComponent(jSeparator27, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(lblEsquadra))
                        .addGap(5, 5, 5)
                        .addComponent(jSeparator28, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(lblTribunal))
                        .addGap(5, 5, 5)
                        .addComponent(jSeparator29, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(lblPena))
                        .addGap(5, 5, 5)
                        .addComponent(jSeparator30, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(lblBloco))
                        .addGap(5, 5, 5)
                        .addComponent(jSeparator31, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(lblCela))
                        .addGap(5, 5, 5)
                        .addComponent(jSeparator32, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
    );

    javax.swing.GroupLayout RelactPanelLayout = new javax.swing.GroupLayout(RelactPanel);
    RelactPanel.setLayout(RelactPanelLayout);
    RelactPanelLayout.setHorizontalGroup(
        RelactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(RelactPanelLayout.createSequentialGroup()
            .addGroup(RelactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(RelactPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(RelactPanelLayout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    RelactPanelLayout.setVerticalGroup(
        RelactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(RelactPanelLayout.createSequentialGroup()
            .addGap(37, 37, 37)
            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(193, Short.MAX_VALUE))
    );

    pnlCards.add(RelactPanel, "RelactPanel");

    HomePanel.setBackground(new java.awt.Color(204, 255, 204));

    letterLabel2.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
    letterLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    letterLabel2.setText("S I S T E M A  D E  G E S T Ã O  ");

    letterLabel3.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
    letterLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    letterLabel3.setText("Bem Vindo");

    letterLabel4.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
    letterLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    letterLabel4.setText("P R I S I O N A L");

    lblNomeG.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
    lblNomeG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblNomeG.setText("Nome:");

    letterLabel6.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
    letterLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    letterLabel6.setText("Nome:");

    lblNomeG1.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
    lblNomeG1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblNomeG1.setText("Turno:");

    lblTurnoG.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
    lblTurnoG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblTurnoG.setText("Turno:");

    tblFuncionario1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
    tblFuncionario1.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null}
        },
        new String [] {
            "Nome", "Endereço", "Sexo", "Estado Civil", "Data de Nascimento", "Data De Admissão", "Função"
        }

    )
    {
        public boolean isCellEditable(int row, int column){
            return false;
        }
    }
    );
    jScrollPane2.setViewportView(tblFuncionario1);

    lblBlocoG.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
    lblBlocoG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblBlocoG.setText("Nome:");

    javax.swing.GroupLayout HomePanelLayout = new javax.swing.GroupLayout(HomePanel);
    HomePanel.setLayout(HomePanelLayout);
    HomePanelLayout.setHorizontalGroup(
        HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(HomePanelLayout.createSequentialGroup()
            .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(HomePanelLayout.createSequentialGroup()
                    .addGap(29, 29, 29)
                    .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(letterLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomePanelLayout.createSequentialGroup()
                            .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(imgLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(letterLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(207, 207, 207))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomePanelLayout.createSequentialGroup()
                            .addComponent(letterLabel4)
                            .addGap(169, 169, 169))))
                .addGroup(HomePanelLayout.createSequentialGroup()
                    .addGap(45, 45, 45)
                    .addComponent(letterLabel6)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(lblNomeG)
                    .addGap(161, 161, 161)
                    .addComponent(lblNomeG1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(lblTurnoG)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
            .addGap(0, 40, Short.MAX_VALUE))
        .addGroup(HomePanelLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane2)
            .addContainerGap())
        .addGroup(HomePanelLayout.createSequentialGroup()
            .addGap(225, 225, 225)
            .addComponent(lblBlocoG)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    HomePanelLayout.setVerticalGroup(
        HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(HomePanelLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(imgLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(letterLabel3)
            .addGap(18, 18, 18)
            .addComponent(letterLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(12, 12, 12)
            .addComponent(letterLabel4)
            .addGap(18, 18, 18)
            .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblNomeG1)
                .addComponent(letterLabel6)
                .addComponent(lblNomeG)
                .addComponent(lblTurnoG))
            .addGap(31, 31, 31)
            .addComponent(lblBlocoG)
            .addGap(44, 44, 44)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(52, Short.MAX_VALUE))
    );

    pnlCards.add(HomePanel, "HomePanel");

    jSplitPane1.setRightComponent(pnlCards);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jSplitPane1)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        dispose();
        new Login().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MousePressed
        // TODO add your handling code here:
        btnSair1.setBackground(ClickedColor);
    }//GEN-LAST:event_jLabel10MousePressed

    private void jLabel10MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseReleased
        // TODO add your handling code here:
        btnSair1.setBackground(defaultColor);
    }//GEN-LAST:event_jLabel10MouseReleased

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        // TODO add your handling code here:
        cardLayout.show(pnlCards, "RelactPanel");
        imgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Icons-Bencao-06.png")));
        CarregarTabelaPris(tblRelactorio);
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel20MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MousePressed
        // TODO add your handling code here:
        btnRelact.setBackground(ClickedColor);
    }//GEN-LAST:event_jLabel20MousePressed

    private void jLabel20MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseReleased
        // TODO add your handling code here:
        btnRelact.setBackground(defaultColor);
    }//GEN-LAST:event_jLabel20MouseReleased

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // TODO add your handling code here:
        cardLayout.show(pnlCards, "HomePanel");
        fController.TabelaG(tbModelF, tblFuncionario1, lblTurnoG.getText(), lblBlocoG.getText(), lblNomeG.getText());
        imgLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Icons-Bencao-04.png")));
        imgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));

    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel21MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MousePressed
        // TODO add your handling code here:
        btnHome.setBackground(ClickedColor);
    }//GEN-LAST:event_jLabel21MousePressed

    private void jLabel21MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseReleased
        // TODO add your handling code here:
        btnHome.setBackground(defaultColor);
    }//GEN-LAST:event_jLabel21MouseReleased

    private void tblRelactorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRelactorioMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            int j = tblRelactorio.getSelectedRow();
            var pris = new Prisioneiro();
            var jPK = new JulgamentoPK();
            var Cr = new Crime();
            var c = new CelaPK();
            var b = new Bloco();
            var ej = new EJulgado();
            var esq = new Esquadra();
            pris.setNome(tbModelPris.getValueAt(j, 1).toString());
            b.setDescricao(Bloco);
            var pController = new PrisioneiroController();
            pController.CarregarRelactPorBloco(pris, Cr, c, b, ej, jPK, esq);

            lblNome.setText(pris.getNome());
            lblBloco.setText(b.getDescricao());
            lblCela.setText(c.getDescricao());
            lblCrime.setText(Cr.getDescricao());
            lblEsquadra.setText(esq.getDescricao());
            lblPena.setText(ej.getPena());
            lblTribunal.setText(jPK.getTribunal());
            lbldataEntrada.setText(pris.getDataEntrada());

        }
    }//GEN-LAST:event_tblRelactorioMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GHome(new Funcionario()).setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HomePanel;
    private javax.swing.JPanel RelactPanel;
    private javax.swing.JPanel btnBloco;
    private javax.swing.JPanel btnCela;
    private javax.swing.JPanel btnFunc;
    private javax.swing.JPanel btnHome;
    private javax.swing.JPanel btnRelact;
    private javax.swing.JPanel btnSair;
    private javax.swing.JPanel btnSair1;
    private javax.swing.JLabel imgLabel;
    private javax.swing.JLabel imgLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator27;
    private javax.swing.JSeparator jSeparator28;
    private javax.swing.JSeparator jSeparator29;
    private javax.swing.JSeparator jSeparator30;
    private javax.swing.JSeparator jSeparator31;
    private javax.swing.JSeparator jSeparator32;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblBloco;
    private javax.swing.JLabel lblBlocoG;
    private javax.swing.JLabel lblCela;
    private javax.swing.JLabel lblCrime;
    private javax.swing.JLabel lblEsquadra;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNomeG;
    private javax.swing.JLabel lblNomeG1;
    private javax.swing.JLabel lblPena;
    private javax.swing.JLabel lblTribunal;
    private javax.swing.JLabel lblTurnoG;
    private javax.swing.JLabel lbldataEntrada;
    private javax.swing.JLabel letterLabel2;
    private javax.swing.JLabel letterLabel3;
    private javax.swing.JLabel letterLabel4;
    private javax.swing.JLabel letterLabel6;
    private javax.swing.JPanel pnlCards;
    private javax.swing.JTable tblFuncionario1;
    private javax.swing.JTable tblRelactorio;
    // End of variables declaration//GEN-END:variables
}
